#include "Grid.h"
#include <iostream>
#include <fstream>
#include <cmath> 
#include "Utils.h"
#include "Mario.h"

#define OBJECT_TYPE_MARIO				0
#define OBJECT_TYPE_BRICK				1
#define OBJECT_TYPE_GOOMBA				2
#define OBJECT_TYPE_KOOPAS				3
#define OBJECT_TYPE_ENVIRONMENT			4
#define OBJECT_TYPE_UPSIDEBRICK			5
#define OBJECT_TYPE_COIN				6
#define OBJECT_TYPE_QBRICK				7
#define OBJECT_TYPE_FIREBALL			8
#define OBJECT_TYPE_FLYGOOMBA			9
#define OBJECT_TYPE_FLYKOOPAS			10
#define OBJECT_TYPE_PLANT				11
#define OBJECT_TYPE_PIRANHAPLANT		12
#define OBJECT_TYPE_SWITCH				13
#define OBJECT_TYPE_BROKENBRICK			14
#define OBJECT_TYPE_PBUTTON				15
#define OBJECT_TYPE_BOARD				16
#define OBJECT_TYPE_PLANTFIREBALL		17
#define OBJECT_TYPE_MUSHROOM			18
#define OBJECT_TYPE_LEAF				19
#define OBJECT_TYPE_ENDPOINTITEM		20
#define OBJECT_TYPE_GAMECLEARBOARD		21
#define OBJECT_TYPE_NUMBER				22
#define OBJECT_TYPE_SPEEDBAR			23
#define OBJECT_TYPE_ITEM				24
#define OBJECT_TYPE_BOOMERANGBROS		25
#define OBJECT_TYPE_BOOMERANG			26
#define OBJECT_TYPE_MOVEBAR				27
#define OBJECT_TYPE_PORTAL				50